//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notatnik.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notatki : INote
    {
        public int id { get; set; }
        public string tytul { get; set; }
        public string tekst { get; set; }
        public System.DateTime data { get; set; }

        public string Tekst()
        {
            return this.tekst;
        }
        public string Tytul()
        {
            return this.tytul;
        }
        public DateTime DataStworzenia()
        {
            return this.data;
        }
    }
}
